cask_args appdir: '/Applications'

tap 'facebook/fb'
tap 'homebrew/bundle'
tap 'Schniz/tap'

# brew 'awscli'
brew 'coreutils'
brew 'fnm'
brew 'git-extras'
brew 'git-fixup'
brew 'grc'
brew 'idb-companion'
brew 'jenv'
brew 'jq'
brew 'jsonpp'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python3'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'tmux'
brew 'wget'
brew 'yarn'

# cask '1password'
cask 'android-studio'
cask 'arc'
cask 'bruno'
# cask 'docker'
cask 'firefox'
cask 'font-fira-code'
cask 'ghostty'
cask 'obsidian'
# cask 'slack'
cask 'spotify'
cask 'tableplus'
# cask 'zoomus'
brew "ripgrep"
cask "gcloud-cli"
brew "googleworkspace-cli"
brew "typescript-language-server"
brew "tree"
